WebText/WebText/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
    url(r'^', include('blog.urls'))
]

WebText/blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^index$', views.index, name='index'),
    url(r'^register$', views.UserRegister, name='register'),
    url(r'^$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^index/add/$', views.create_blog, name='add_blog'),
]

WebText/blog/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import Permission, User

class blogmod(models.Model):
    user = models.ForeignKey(User, default=1)
    title=models.CharField(max_length=50)
    blog_text = models.CharField(max_length=500)
    date = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.title + '-' + self.blog_text

WebText/blog/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import blogmod

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class BlogForm(forms.ModelForm):

    class Meta:
        model = blogmod
        fields = ['title', 'blog_text', 'date']

WebText/blog/views.py
from .models import blogmod

from .forms import UserForm,BlogForm
from django.shortcuts import render, redirect
from django.contrib.auth import  authenticate, login, logout

from django.db.models import Q



def index(request):
    if not request.user.is_authenticated():
        return render(request, 'blog/login.html')
    else:
        all_blog = blogmod.objects.filter(user=request.user)
        query = request.GET.get("q")
        if query:
            albums = all_blog.filter(
                Q(album_title__icontains=query) |
                Q(artist__icontains=query)
            ).distinct()
            return render(request, 'blog/index.html', {'all_blog': all_blog})
        else:
            return render(request, 'blog/index.html', {'all_blog': all_blog})



def create_blog(request):
    if not request.user.is_authenticated():
        return render(request, 'blog/login.html')
    else:
        form = BlogForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            all_blog = form.save(commit=False)
            all_blog.user = request.user
            all_blog.save()
            return redirect('blog:index')
        context = {
            "form": form,
        }
        return render(request, 'blog/blogmod_form.html', context)

def UserRegister(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                all_blog = blogmod.objects.filter(user=request.user)
                return render(request, 'blog/index.html', {'all_blog': all_blog})
    context = {
        "form": form,
    }
    return render(request, 'blog/registration_form.html', context)



def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'blog/login.html', context)

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                all_blog = blogmod.objects.filter(user=request.user)
                return render(request, 'blog/index.html', {'all_blog': all_blog})
            else:
                return render(request, 'blog/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'blog/login.html', {'error_message': 'Invalid login'})
    return render(request, 'blog/login.html')

WebText/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    {% load staticfiles %}
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'blog/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'blog/css/1-col-portfolio.css' %}" rel="stylesheet">

     <!-- jQuery -->
    <script src="{% static 'blog/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->



    <title>My Account</title>

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{%  url 'blog:register' %}">My Account</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'blog:add_blog' %}">Add Blog</a>
                    </li>
                    <li>
                        <a href="{% url 'blog:logout_user' %}">Logout</a>
                    </li>

                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

{% block body %}

{% endblock %}



</body>

</html>

WebText/blog/templates/blog/blogmod_form.html
 {% extends 'blog/base.html' %}


 {% block body %}
 <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
     {% csrf_token %}
     {% for field in form %}
     <div class="form-group">
         <label class="control-label col-sm-2">
             {{ field.label_tag }}
         </label>
         <div class="col-sm-10">
             {{field}}
         </div>
     </div>
     {%  endfor %}

     <div class="form-group">
         <div class="col-sm-offset-2 col-sm-10">
             <button type="submit" class="btn btn-success">Submit</button>
        </div>
     </div>
 </form>

 {% endblock %}

WebText/blog/templates/blog/form_template.html
{% for field in form %}
    <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <span class="text-danger small">{{field_error}}</span>
            </div>
            <label class="control-label col-sm-2">
             {{ field.label_tag }}
            </label>
            <div class="col-sm-10">
             {{field}}
            </div>
    </div>
{%  endfor %}

WebText/blog/templates/blog/index.html
{% extends 'blog/base.html' %}

 {% block body %}
    <!-- Page Content -->
    <div class="container">

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Heading
                    <small>Secondary Text</small>
                </h1>
            </div>
        </div>
        {% if all_blog %}
            <!-- /.row -->
            {% for eachblog in all_blog %}
            <!-- Project One -->
            <div class="row">
                <div class="col-md-12">
                    <h3>{{ eachblog.title }}</h3>
                    <h4> Created On {{eachblog.date}} </h4>
                    <p>{{ eachblog.blog_text }}</p>
                </div>
            </div>
            <hr>
            <!-- /.row -->
            {% endfor %}
        {% else %}
                <h3>No Post, Please Write Something</h3>
        {% endif %}
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; MyAccount 2016</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->
 {% endblock %}

WebText/blog/templates/blog/login.html
{% extends 'blog/visitor_nav.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'blog:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'blog:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

WebText/blog/templates/blog/registration_form.html
{% extends 'blog/visitor_nav.html' %}


{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'blog/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'blog:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

WebText/blog/templates/blog/visitor_nav.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Blogs{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'blog/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'blog:login_user' %}">MyAccount</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'blog:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'blog:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>